
version: '3.3'

services: 
    jenkins:
        image: terryvdgriend/workshop-jenkins
        ports: 
            - "8080:8080"
        volumes: 
            - "/var/run/docker.sock:/var/run/docker.sock"
